SELECT DISTINCT ?language ?languageLabel ?iso639_3 ?parent ?parentLabel WHERE {
  ?language wdt:P220 ?iso639_3.
  ?language wdt:P31 ?type.
  ?language wdt:P279 ?parent.
  ?type wdt:P279* wd:Q34770.
  SERVICE wikibase:label {bd:serviceParam wikibase:language "en".}
}
ORDER BY ?language